const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;
const CONFLICT_ERROR = 409;
const AUTHORIZATION_ERROR = 401;
const FORBIDDEN_ERROR = 403;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  CONFLICT_ERROR,
  AUTHORIZATION_ERROR,
  FORBIDDEN_ERROR,
};
